server:
  port: 8080
  servlet:
    session:
      timeout: 32400
  error:
    include-stacktrace: always
    include-exception: true
logging:
  config: classpath:logback-${spring.profiles.active}.xml
  level:
    root: info

### spring ############################################################
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://bazzarmall.cafe24.com:3306/bazzarmall
    username: bazzarmall
    password: Tower@545271   
    #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #url: jdbc:log4jdbc:mariadb://mariadb-live-chorok.cqxvmdetneem.ap-northeast-2.rds.amazonaws.com:3306/chorokdb
    #username: chorokadm
    #password: Tower@545271
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 30
      max-lifetime: 1800000
      pool-name: HikariCP
      read-only: false
      connection-test-query: SELECT 1 FROM DUAL
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  banner:
    location: banner_account.txt

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

### MyBatis############################################################
mybatis:
  mapper-locations: mapper/**/*.xml # mapper.xml 위치 지정
  configuration:
    map-underscore-to-camel-case: true # model 프로퍼티 camel case 설정