server:
    port: 8080

logging:  level:    root: info

### spring ############################################################
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@sunja.asuscomm.com:1521/xe
    username: CHOROK
    password: tower0814
    hikari:       connection-timeout: 30000
      maximum-pool-size: 10
      max-lifetime: 1800000
      pool-name: HikariCP
      read-only: false
      connection-test-query: SELECT 1 FROM DUAL

  banner:
    location: banner_account.txt    
        
       
### MyBatis ############################################################

mybatis:
  mapper-locations: mapper/**/*.xml # mapper.xml 위치 지정
  configuration:
    map-underscore-to-camel-case: true # model 프로퍼티 camel case 설정